### ISSUE TITLE
add binary to build artifacts

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/mock-server#81]
**Is your feature request related to a problem? Please describe.**
i’d like binary builds for artifacts so that i can brew or apt-get or maybe even chocolatey install the mock server without having nodejs installed

**Comment by BelfordZ** [comment]
I think his would be great. Resolution to this issue should include:
 - [ ] macos/linux/windows 32/64 bit builds
 - [ ] the builds being added to github releases via semantic-release & circle ci
 - [ ] script that releases to brew?

Also, perhaps we can explore providing mock-server written in rust or go instead of ts?
